export const refineResources = [
  { name: 'brands', list: '/admin/catalog/brands', meta: { feature: 'catalog-taxonomy' } },
  { name: 'categories', list: '/admin/catalog/categories', meta: { feature: 'catalog-taxonomy' } },
  { name: 'option_types', list: '/admin/catalog/options', meta: { feature: 'catalog-taxonomy' } },
  { name: 'option_values', list: '/admin/catalog/options', meta: { feature: 'catalog-taxonomy' } },
  { name: 'products', list: '/admin/products', meta: { feature: 'product-catalog' } },
  { name: 'product_categories', meta: { feature: 'product-catalog' } },
  { name: 'product_variants', meta: { feature: 'product-catalog' } },
  { name: 'variant_option_values', meta: { feature: 'product-catalog' } },
  { name: 'product_variant_media', meta: { feature: 'media-library' } },
  { name: 'inventory', list: '/admin/inventory', meta: { feature: 'inventory' } },
  { name: 'inventory_adjustments', meta: { feature: 'inventory' } },
  { name: 'orders', list: '/admin/orders', meta: { feature: 'orders' } },
  { name: 'media_assets', list: '/admin/media', meta: { feature: 'media-library' } },
  { name: 'profiles', list: '/admin/users', meta: { feature: 'admin-users', privileged: true } },
  { name: 'store_settings', list: '/admin/settings', meta: { feature: 'store-settings' } },
];
