export const refineResources = [
  { name: 'brands', list: '/admin/catalog/brands', meta: { feature: 'catalog-taxonomy' } },
  { name: 'categories', list: '/admin/catalog/categories', meta: { feature: 'catalog-taxonomy' } },
  { name: 'option-types', list: '/admin/catalog/options', meta: { feature: 'catalog-taxonomy' } },
  { name: 'option-values', list: '/admin/catalog/options', meta: { feature: 'catalog-taxonomy' } },
  { name: 'products', list: '/admin/products', meta: { feature: 'product-catalog' } },
  { name: 'product-categories', meta: { feature: 'product-catalog' } },
  { name: 'product-variants', meta: { feature: 'product-catalog' } },
  { name: 'variant-option-values', meta: { feature: 'product-catalog' } },
  { name: 'product-variant-media', meta: { feature: 'media-library' } },
  { name: 'inventory', list: '/admin/inventory', meta: { feature: 'inventory' } },
  { name: 'inventory-adjustments', meta: { feature: 'inventory' } },
  { name: 'orders', list: '/admin/orders', meta: { feature: 'orders' } },
  { name: 'media-assets', list: '/admin/media', meta: { feature: 'media-library' } },
  { name: 'admin-users', list: '/admin/users', meta: { feature: 'admin-users' } },
  { name: 'store-settings', list: '/admin/settings', meta: { feature: 'store-settings' } },
];
