'use client';

import { useCallback, useEffect, useState } from 'react';

import type { OptionTypeRecord } from '@/features/catalog-taxonomy/types';
import {
  KisokButton,
  KisokDialog,
  KisokDialogContent,
  KisokDialogDescription,
  KisokDialogFooter,
  KisokDialogHeader,
  KisokDialogTitle,
  StatusPill,
} from '@/shared/ui';

import { productCatalogRepository } from '../repositories';
import type { ProductRecord, VariantRecord } from '../types';
import { VariantFormDialog } from './VariantFormDialog';
import { VariantOptionsDialog } from './VariantOptionsDialog';

type VariantDialogState =
  | { open: false }
  | { open: true; mode: 'create' }
  | { open: true; mode: 'edit'; variant: VariantRecord };

export function VariantManagerDialog({
  open,
  onOpenChange,
  product,
  optionTypes,
  onVariantsChanged,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  product: ProductRecord | null;
  optionTypes: OptionTypeRecord[];
  onVariantsChanged: () => void;
}) {
  const [variants, setVariants] = useState<VariantRecord[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formDialog, setFormDialog] = useState<VariantDialogState>({ open: false });
  const [optionsVariant, setOptionsVariant] = useState<VariantRecord | null>(null);

  const refreshVariants = useCallback(async (productId: string) => {
    setIsLoading(true);
    setError(null);
    try {
      setVariants(await productCatalogRepository.listVariants(productId));
    } catch {
      setError('Variants could not be loaded.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  const productId = product?.id ?? null;
  useEffect(() => {
    if (!(open && productId)) return;
    void refreshVariants(productId);
  }, [open, productId, refreshVariants]);

  if (!product) return null;

  return (
    <KisokDialog onOpenChange={onOpenChange} open={open}>
      <KisokDialogContent>
        <KisokDialogHeader>
          <KisokDialogTitle>Variants · {product.name}</KisokDialogTitle>
          <KisokDialogDescription>
            Variant SKUs are generated by Lean V2. Maintain only operational identifiers, stock
            thresholds, and Option combinations here.
          </KisokDialogDescription>
        </KisokDialogHeader>

        {isLoading ? (
          <p className="text-muted-foreground text-sm" role="status">
            Loading variants…
          </p>
        ) : error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : variants.length === 0 ? (
          <p className="text-muted-foreground text-sm">No variants are assigned to this Product.</p>
        ) : (
          <div className="divide-y divide-border border-border border-y">
            {variants.map((variant) => (
              <div className="flex items-center justify-between gap-3 py-3" key={variant.id}>
                <div>
                  <p className="font-mono text-sm">{variant.sku}</p>
                  <p className="text-muted-foreground text-xs">
                    {variant.titleOverride ??
                      'No title override — display name derives from selected Options'}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <StatusPill
                    className={variant.isActive ? undefined : 'border-destructive text-destructive'}
                  >
                    {variant.isActive ? 'Active' : 'Inactive'}
                  </StatusPill>
                  <KisokButton
                    aria-label={`Options ${variant.sku}`}
                    onClick={() => setOptionsVariant(variant)}
                    size="sm"
                    variant="quiet"
                  >
                    Options
                  </KisokButton>
                  <KisokButton
                    aria-label={`Edit ${variant.sku}`}
                    onClick={() => setFormDialog({ open: true, mode: 'edit', variant })}
                    size="sm"
                    variant="quiet"
                  >
                    Edit
                  </KisokButton>
                </div>
              </div>
            ))}
          </div>
        )}

        <KisokDialogFooter>
          <KisokButton onClick={() => onOpenChange(false)} variant="quiet">
            Close
          </KisokButton>
          <KisokButton onClick={() => setFormDialog({ open: true, mode: 'create' })}>
            Add variant
          </KisokButton>
        </KisokDialogFooter>
      </KisokDialogContent>

      {formDialog.open && formDialog.mode === 'create' ? (
        <VariantFormDialog
          mode="create"
          onCreate={async (input) => {
            await productCatalogRepository.createVariant(input);
            await refreshVariants(product.id);
            onVariantsChanged();
          }}
          onOpenChange={(next) => {
            if (!next) setFormDialog({ open: false });
          }}
          open={formDialog.open}
          productId={product.id}
        />
      ) : null}

      {formDialog.open && formDialog.mode === 'edit' ? (
        <VariantFormDialog
          mode="edit"
          onOpenChange={(next) => {
            if (!next) setFormDialog({ open: false });
          }}
          onUpdate={async (id, input) => {
            await productCatalogRepository.updateVariant(id, input);
            await refreshVariants(product.id);
            onVariantsChanged();
          }}
          open={formDialog.open}
          variant={formDialog.variant}
        />
      ) : null}

      {optionsVariant ? (
        <VariantOptionsDialog
          onOpenChange={(next) => {
            if (!next) setOptionsVariant(null);
          }}
          open={optionsVariant !== null}
          optionTypes={optionTypes}
          variantId={optionsVariant.id}
          variantLabel={optionsVariant.sku}
        />
      ) : null}
    </KisokDialog>
  );
}
