'use client';

import { useEffect, useState } from 'react';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';

import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import {
  KisokButton,
  KisokDialog,
  KisokDialogContent,
  KisokDialogDescription,
  KisokDialogFooter,
  KisokDialogHeader,
  KisokDialogTitle,
  KisokInput,
} from '@/shared/ui';

import {
  type VariantEditorFormValues,
  type VariantEditorValues,
  variantEditorDefaultValues,
  variantEditorSchema,
} from '../schemas/variant-editor.schema';
import type { VariantInput, VariantRecord, VariantUpdate } from '../types';

type CreateProps = {
  mode: 'create';
  productId: string;
  onCreate: (input: VariantInput) => Promise<void>;
  onUpdate?: undefined;
  variant?: undefined;
};

type EditProps = {
  mode: 'edit';
  onCreate?: undefined;
  onUpdate: (id: string, input: VariantUpdate) => Promise<void>;
  productId?: undefined;
  variant: VariantRecord;
};

type VariantFormDialogProps = (CreateProps | EditProps) & {
  onOpenChange: (open: boolean) => void;
  open: boolean;
};

function toFormValues(variant?: VariantRecord): VariantEditorFormValues {
  if (!variant) return variantEditorDefaultValues;
  return {
    barcode: variant.barcode ?? '',
    isActive: variant.isActive,
    lowStockThreshold: variant.lowStockThreshold === null ? '' : String(variant.lowStockThreshold),
    titleOverride: variant.titleOverride ?? '',
  };
}

export function VariantFormDialog(props: VariantFormDialogProps) {
  const { mode, onOpenChange, open } = props;
  const form = useForm<VariantEditorFormValues, undefined, VariantEditorValues>({
    defaultValues: variantEditorDefaultValues,
    resolver: zodResolver(variantEditorSchema),
  });
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const editVariant = mode === 'edit' ? props.variant : undefined;

  useEffect(() => {
    if (!open) return;
    form.reset(toFormValues(editVariant));
    setError(null);
  }, [editVariant, form, open]);

  async function save(values: VariantEditorValues) {
    setIsSaving(true);
    setError(null);
    try {
      if (mode === 'create') {
        await props.onCreate({
          barcode: values.barcode,
          lowStockThreshold: values.lowStockThreshold,
          productId: props.productId,
          titleOverride: values.titleOverride,
        });
      } else {
        await props.onUpdate(props.variant.id, {
          barcode: values.barcode,
          isActive: values.isActive,
          lowStockThreshold: values.lowStockThreshold,
          titleOverride: values.titleOverride,
        });
      }
      onOpenChange(false);
    } catch (caughtError) {
      setError(
        caughtError instanceof Error ? caughtError.message : 'The Variant could not be saved.',
      );
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <KisokDialog onOpenChange={onOpenChange} open={open}>
      <KisokDialogContent>
        <KisokDialogHeader>
          <KisokDialogTitle>{mode === 'create' ? 'Add Variant' : 'Edit Variant'}</KisokDialogTitle>
          <KisokDialogDescription>
            SKU is generated by Lean V2 and cannot be edited. A title override is an advanced,
            exception-only field; normal Variant names derive from their selected Option Values.
          </KisokDialogDescription>
        </KisokDialogHeader>

        <form className="grid gap-4" onSubmit={(event) => void form.handleSubmit(save)(event)}>
          {mode === 'edit' ? (
            <div className="grid gap-2">
              <span className="font-mono text-[10px] text-muted-foreground uppercase tracking-[0.16em]">
                SKU
              </span>
              <p className="font-mono text-sm">{props.variant.sku}</p>
            </div>
          ) : null}

          <div className="grid gap-2">
            <Label htmlFor="variant-barcode">Barcode</Label>
            <KisokInput id="variant-barcode" {...form.register('barcode')} />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="variant-title-override">
              Title override (advanced / exception only)
            </Label>
            <KisokInput id="variant-title-override" {...form.register('titleOverride')} />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="variant-threshold">Low-stock threshold</Label>
            <KisokInput
              id="variant-threshold"
              inputMode="numeric"
              {...form.register('lowStockThreshold')}
            />
            {form.formState.errors.lowStockThreshold ? (
              <p className="text-destructive text-sm">
                {form.formState.errors.lowStockThreshold.message}
              </p>
            ) : null}
          </div>
          {mode === 'edit' ? (
            <div className="flex items-center gap-2">
              <Checkbox
                checked={form.watch('isActive')}
                id="variant-active"
                onCheckedChange={(checked) =>
                  form.setValue('isActive', checked === true, { shouldDirty: true })
                }
              />
              <Label htmlFor="variant-active">Active</Label>
            </div>
          ) : null}

          {error ? (
            <p className="text-destructive text-sm" role="alert">
              {error}
            </p>
          ) : null}
          <KisokDialogFooter>
            <KisokButton
              disabled={isSaving}
              onClick={() => onOpenChange(false)}
              type="button"
              variant="quiet"
            >
              Cancel
            </KisokButton>
            <KisokButton disabled={isSaving} type="submit">
              {isSaving ? 'Saving…' : 'Save variant'}
            </KisokButton>
          </KisokDialogFooter>
        </form>
      </KisokDialogContent>
    </KisokDialog>
  );
}
