'use client';

import { useEffect, useState } from 'react';

import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import {
  KisokButton,
  KisokDialog,
  KisokDialogContent,
  KisokDialogDescription,
  KisokDialogFooter,
  KisokDialogHeader,
  KisokDialogTitle,
  KisokInput,
} from '@/shared/ui';

import type { VariantInput, VariantRecord, VariantUpdate } from '../types';

type CreateProps = {
  mode: 'create';
  productId: string;
  onCreate: (input: VariantInput) => Promise<void>;
  variant?: undefined;
  onUpdate?: undefined;
};

type EditProps = {
  mode: 'edit';
  variant: VariantRecord;
  onUpdate: (id: string, input: VariantUpdate) => Promise<void>;
  productId?: undefined;
  onCreate?: undefined;
};

type VariantFormDialogProps = (CreateProps | EditProps) & {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function VariantFormDialog(props: VariantFormDialogProps) {
  const { open, onOpenChange, mode } = props;
  const [barcode, setBarcode] = useState('');
  const [titleOverride, setTitleOverride] = useState('');
  const [lowStockThreshold, setLowStockThreshold] = useState('5');
  const [isActive, setIsActive] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const editVariant = mode === 'edit' ? props.variant : undefined;

  useEffect(() => {
    if (!open) return;
    if (editVariant) {
      setBarcode(editVariant.barcode ?? '');
      setTitleOverride(editVariant.titleOverride ?? '');
      setLowStockThreshold(String(editVariant.lowStockThreshold ?? ''));
      setIsActive(editVariant.isActive);
    } else {
      setBarcode('');
      setTitleOverride('');
      setLowStockThreshold('5');
      setIsActive(true);
    }
    setError(null);
  }, [open, editVariant]);

  async function handleSubmit() {
    setIsSaving(true);
    setError(null);
    const threshold = lowStockThreshold.trim() === '' ? null : Number(lowStockThreshold);
    try {
      if (mode === 'create') {
        await props.onCreate({
          productId: props.productId,
          barcode: barcode.trim() || null,
          titleOverride: titleOverride.trim() || null,
          lowStockThreshold: threshold,
        });
      } else {
        await props.onUpdate(props.variant.id, {
          barcode: barcode.trim() || null,
          titleOverride: titleOverride.trim() || null,
          lowStockThreshold: threshold,
          isActive,
        });
      }
      onOpenChange(false);
    } catch (caughtError) {
      setError(
        caughtError instanceof Error ? caughtError.message : 'The Variant could not be saved.',
      );
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <KisokDialog onOpenChange={onOpenChange} open={open}>
      <KisokDialogContent>
        <KisokDialogHeader>
          <KisokDialogTitle>{mode === 'create' ? 'Add variant' : 'Edit variant'}</KisokDialogTitle>
          <KisokDialogDescription>
            SKU is generated by Lean V2 and cannot be edited. Title override is an advanced,
            exception-only field — a Variant's normal display name derives from its selected Option
            Values, managed separately under Options.
          </KisokDialogDescription>
        </KisokDialogHeader>

        <div className="grid gap-4">
          {mode === 'edit' ? (
            <div className="grid gap-2">
              <span className="font-mono text-[10px] text-muted-foreground uppercase tracking-[0.16em]">
                SKU
              </span>
              <p className="font-mono text-sm">{props.variant.sku}</p>
            </div>
          ) : null}

          <div className="grid gap-2">
            <Label htmlFor="variant-barcode">Barcode</Label>
            <KisokInput
              id="variant-barcode"
              onChange={(event) => setBarcode(event.target.value)}
              value={barcode}
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="variant-title-override">
              Title override (advanced / exception only)
            </Label>
            <KisokInput
              id="variant-title-override"
              onChange={(event) => setTitleOverride(event.target.value)}
              value={titleOverride}
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="variant-threshold">Low-stock threshold</Label>
            <KisokInput
              id="variant-threshold"
              inputMode="numeric"
              onChange={(event) => setLowStockThreshold(event.target.value)}
              value={lowStockThreshold}
            />
          </div>

          {mode === 'edit' ? (
            <div className="flex items-center gap-2">
              <Checkbox
                checked={isActive}
                id="variant-active"
                onCheckedChange={(checked) => setIsActive(checked === true)}
              />
              <Label htmlFor="variant-active">Active</Label>
            </div>
          ) : null}
        </div>

        {error ? (
          <p className="text-destructive text-sm" role="alert">
            {error}
          </p>
        ) : null}

        <KisokDialogFooter>
          <KisokButton
            disabled={isSaving}
            onClick={() => onOpenChange(false)}
            type="button"
            variant="quiet"
          >
            Cancel
          </KisokButton>
          <KisokButton disabled={isSaving} onClick={() => void handleSubmit()} type="button">
            {isSaving ? 'Saving…' : 'Save variant'}
          </KisokButton>
        </KisokDialogFooter>
      </KisokDialogContent>
    </KisokDialog>
  );
}
